export const notesApi = {
  addNotes: "api/notes/addNotes",
  updateNotes: "api/notes/updateNotes",
  changesColorNotes: "api/notes/changesColorNotes",
  pinUnpinNotes: "api/notes/pinUnpinNotes",
  archiveNotes: "api/notes/archiveNotes",
  trashNotes: "api/notes/trashNotes",
  addOrUpdateReminder: "api/notes/addUpdateReminderNotes",
  deleteForeverNotes: "api/notes/deleteForeverNotes",
  removeReminder: "api/notes/removeReminderNotes",
  getNotesList: "api/notes/getNotesList",
  getArchiveNotesList: "api/notes/getArchiveNotesList",
  getTrashNotesList: "api/notes/getTrashNotesList",
  noteLabels: "api/noteLabels",
  getNoteLabelList: "api/noteLabels/getNoteLabelList",
  deleteLabel: "/deleteNoteLabel",
  updateLabel: "/updateNoteLabel",
  addOrRemoveLabelFromNoteStartUrl: "api/notes/",
  addOrRemoveLabelFromNoteMiddleUrl: "/addLabelToNotes/",
  removeLabelFromNoteEndUrl: "/remove",
  addLabelFromNoteEndUrl: "/add",
  userSearchList: "api/user/searchUserList",
  addCollaboratorNotes: "/AddcollaboratorsNotes",
  removeCollaboratorsNotes: "/removeCollaboratorsNotes/",
  getNotesListByLabel: "getNotesListByLabel/",
};
